### ISSUE TITLE
Search appears outdated

### ISSUE THREAD

**Issue by jpw** [npms-io/npms-www#231] opened 2019-09-16 13:01 UTC
Hi there!

We're seeing the search is outdated again, as per #230
e.g.
https://npms.io/search?q=%40springernature%2Fglobal-context is at 3.0.0, 2019-07-31
https://www.npmjs.com/package/@springernature/global-context should be 4.0.1 as of 3 days ago

Thanks for having a look.

**Comment by noobling** [comment] 2019-10-03 09:07
Yeah a few packages seem to be outdated...

**Comment by satazor** [comment] 2021-10-26 12:29
Duplicate of https://github.com/npms-io/npms-api/issues/101

**Closed as completed by satazor** 2021-10-26 12:29 UTC
