### ISSUE TITLE
Searching for a module by exact name

### ISSUE THREAD

**Issue by guigrpa** [npms-io/npms-www#21] opened 2016-06-13 07:14 UTC
While I find this tool useful for package discovery, it doesn't seem to work as expected when you **look for a package by its name**. Try _uglifyjs_, for instance: you have to scroll almost all the way down the 127-result list to find the one you're looking for. Try _react_: I was not able to find it at all!

What about including in the first place the module by that name? This is also something that I find lacking in the _official_ npmjs.com site, but at least I can easily find _react_ :)

**Comment by satazor** [comment] 2016-06-13 08:18
Duplicate of https://github.com/npms-io/npms-analyzer/issues/48

**Comment by satazor** [comment] 2016-06-13 13:09
@guigrpa the issue is now fixed, give it a try!

**Comment by guigrpa** [comment] 2016-06-13 13:29
@satazor Tried _uglifyjs_ and _react_ and it works like a charm. With _Uglifyjs_ (capital U), however, it fails — notice that npm is case-insensitive, though.

**Comment by satazor** [comment] 2016-06-13 13:30
Hmm let me investigate

**Comment by satazor** [comment] 2016-06-13 13:40
Fixed in https://github.com/npms-io/npms-api/commit/84b8346c4b217c2cc364cb0f1c52bc23a68b8357! Thanks again for reporting.

**Closed as completed by satazor** 2016-06-13 13:40 UTC

**Comment by guigrpa** [comment] 2016-06-13 13:51
Thanks to you for the fast fix!
