### ISSUE TITLE
npms.io search doesn't work

### ISSUE THREAD

**Issue by ventsislav-georgiev** [npms-io/npms-www#183] opened 2017-09-13 10:34 UTC
![image](https://user-images.githubusercontent.com/5616486/30372926-3a1fa8a8-9888-11e7-9cda-3d9a0c4da958.png)

**Comment by satazor** [comment] 2017-09-13 11:45
Duplicate of https://github.com/npms-io/npms-api/issues/69#issuecomment-328943304

**Closed as completed by satazor** 2017-09-13 11:45 UTC
